name: Sincronizar Datos FIFA

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar script de extracción
        run: python scraper.py

      - name: Subir el nuevo JSON al repositorio
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Sincronizador FIFA"
          git add datos_fifa.json
          git commit -m "Actualización automática de resultados" || echo "No hay cambios para subir"
          git push
